### ISSUE TITLE
Anatomist import fails in the brainvisa.anatomist module

### ISSUE THREAD

**Issue by ylep** [brainvisa/anatomist-gpl#17]
[Test fail on the master branch](https://brainvisa.info/builds/view/branch%20master/job/cea-master-5.0/858/consoleFull) because `brainvisa.anatomist` the module fails to contain the `Anatomist` object:

```
QApplication already instantiated, headless Anatomist is not possible.


ERROR: **

    
    
    AttributeError: /casa/host/build/brainvisa/toolboxes/baby/processes/Components/baby_histo_analysis.py: 'module' object has no attribute 'Anatomist'

**

* * *

`**AttributeError**`

    
    
    Traceback (most recent call last):
      File "/casa/host/build/python/brainvisa/processes.py", line 6363, in addDir
        toolbox=toolbox)  # two arguments : process fullpath and category (directories separated by /)
      File "/casa/host/build/python/brainvisa/processes.py", line 5948, in readProcess
        sys.exc_info()[2])
      File "/casa/host/build/python/brainvisa/processes.py", line 5933, in readProcess
        moduleName, fileIn, fileName, moduleDescription)
      File "/casa/host/build/brainvisa/toolboxes/baby/processes/Components/baby_histo_analysis.py", line 6, in <module>
        from brainvisa import anatomist
      File "/casa/host/build/python/brainvisa/anatomist/__init__.py", line 107, in <module>
        class Anatomist(anatomistModule.Anatomist):
    AttributeError: /casa/host/build/brainvisa/toolboxes/baby/processes/Components/baby_histo_analysis.py: 'module' object has no attribute 'Anatomist'
```

@denisri I guess this is probably related to https://github.com/brainvisa/anatomist-gpl/commit/765888e2f33c3fcd6bd727feb2127aff0edf80d7 and/or https://github.com/brainvisa/anatomist-gpl/commit/2aa74cddf3e4d739eded77b26917b8fcbc3400e7 ?

**Comment by denisri** [comment]
The problem is in axon. I transfer the ticket
